version: "3"

services:
    db:
        image: postgres:11.0

    php:
        # Important so we can reference it later
        container_name: php_blockchain_explorer
        build: docker/php

    nginx:
        build: docker/nginx

    ofelia:
        image: mcuadros/ofelia
