version: "3"

services:
    db:
        container_name: db_blockchain_explorer
        image: postgres:11.0

    php:
        # Important so we can reference it later
        container_name: php_blockchain_explorer
        build: docker/php

    nginx:
        container_name: nginx_blockchain_explorer
        build: docker/nginx

    ofelia:
        container_name: ofelia_blockchain_explorer
        image: mcuadros/ofelia
